apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-html
  namespace: taskboard
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head><title>TaskBoard - AKS Project 07</title></head>
    <body style="font-family:Arial;max-width:600px;margin:40px auto;padding:20px">
      <h2 style="color:#0078d4">TaskBoard — AKS Project 07</h2>
      <div id="tasks">Loading...</div>
      <p id="pod" style="color:#aaa;font-size:12px"></p>
      <script>
        fetch('/api/')
          .then(r => r.json())
          .then(d => {
            document.getElementById('tasks').innerHTML =
              d.tasks.map(t => '<p>' + t.status + ' — ' + t.title + '</p>').join('');
            document.getElementById('pod').textContent = 'Served by Pod: ' + d.servedBy;
          });
      </script>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: taskboard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: taskboard
      tier: frontend
  template:
    metadata:
      labels:
        app: taskboard
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: nginx:1.25-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html-volume
              mountPath: /usr/share/nginx/html
          resources:
            requests:
              cpu: "50m"
              memory: "64Mi"
            limits:
              cpu: "100m"
              memory: "128Mi"
      volumes:
        - name: html-volume
          configMap:
            name: frontend-html
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: taskboard
spec:
  selector:
    app: taskboard
    tier: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer